#########################
# Computer Vision - DOG #
#########################
@region1=westus
# Computer Vision (Microsoft Trained Model) with a dog photo
# https://westus.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-2/
GET http://1.bp.blogspot.com/-tTKQzYelLXw/UOMOFot4pRI/AAAAAAAAAEE/wyFoaSSI06I/s1600/cute-pets-maltese-dog-pictures+(8).jpg
####
POST https://{{region1}}.api.cognitive.microsoft.com/vision/v3.2/analyze?language=en
&model-version=latest
Ocp-Apim-Subscription-Key: {{computerVisionSubscription}}
Content-Type: application/json

{
    "url": "http://1.bp.blogspot.com/-tTKQzYelLXw/UOMOFot4pRI/AAAAAAAAAEE/wyFoaSSI06I/s1600/cute-pets-maltese-dog-pictures+(8).jpg"
}

#########################
# Custom Vision - VALID #
#########################
# https://www.customvision.ai/
####
# Custom Vision (Custom Trained) with a license plate here
# VALID Lcense Plate
@region2 = southcentralus
GET https://upload.wikimedia.org/wikipedia/commons/9/90/1996_California_license_plate_5PPP064_Flickr_-_woody1778a.jpg

####
POST https://{{region2}}.api.cognitive.microsoft.com/customvision/v3.0/Prediction/8f9df053-87e3-42b4-b62f-ad7c55db44be/classify/iterations/Iteration18/url
Prediction-Key: {{customVisionSubscription}}
Content-Type: application/json

{
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/90/1996_California_license_plate_5PPP064_Flickr_-_woody1778a.jpg"
}

###########################
# Custom Vision - INVALID #
###########################

####
# Custom Vision (Custom Trained) with a license plate here
# INVALID Lcense Plate
GET https://i.ebayimg.com/images/i/252918278713-0-1/s-l1000.jpg
####
POST https://{{region2}}.api.cognitive.microsoft.com/customvision/v3.0/Prediction/8f9df053-87e3-42b4-b62f-ad7c55db44be/classify/iterations/Iteration18/url
Prediction-Key: {{customVisionSubscription}}
Content-Type: application/json

{
    "url": "https://i.ebayimg.com/images/i/252918278713-0-1/s-l1000.jpg"
}


####
GET https://images.homedepot-static.com/productImages/a5a1508a-ed34-42c0-81cd-f26c9bd483e1/svn/robtec-hex-bolts-rti2322609-64_1000.jpg
