
# https://www.luis.ai/

@region=westus
####
# LUIS Intent Take 1 
# Requires an application be setup and trained.  Please see the following to create and train a LUIS app.
# https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-get-started-create-app


GET https://{{region}}.api.cognitive.microsoft.com/luis/prediction/v3.0/apps/{{luisAppId}}/slots/production/predict?subscription-key={{luisSubscription}}
&verbose=true
&show-all-intents=true
&log=true
&query="Hello there!"

####
# LUIS Intent Take 2 
# Requires an application be setup and trained.  Please see the following to create and train a LUIS app.
# https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-get-started-create-app
GET https://{{region}}.api.cognitive.microsoft.com/luis/prediction/v3.0/apps/{{luisAppId}}/slots/production/predict?subscription-key={{luisSubscription}}
&verbose=true
&show-all-intents=true
&log=true
&query="Find my landscape photos"


####
# LUIS Intent Take 2 
# Requires an application be setup and trained.  Please see the following to create and train a LUIS app.
# https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-get-started-create-app
GET https://{{region}}.api.cognitive.microsoft.com/luis/prediction/v3.0/apps/{{luisAppId}}/slots/production/predict?subscription-key={{luisSubscription}}
&verbose=true
&show-all-intents=true
&log=true
&query="Book my tickets"